CREATE TABLE `tennis_match` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `challenger_id` int(11) NOT NULL,
  `acceptor_id` int(11) NOT NULL,
  `match_date` date NOT NULL,
  `match_time` time NOT NULL,
  `venue` varchar(255) NOT NULL,
  `challenger_partner_id` int(11) DEFAULT NULL,
  `acceptor_partner_id` int(11) DEFAULT NULL,
  `challenger_partner_name` varchar(255) DEFAULT NULL,
  `acceptor_partner_name` varchar(255) DEFAULT NULL,
  `game_type` varchar(255) DEFAULT NULL,
  `number_of_sets` int(11) NOT NULL,
  `challenger_score` varchar(255) DEFAULT NULL,
  `acceptor_score` varchar(255) DEFAULT NULL,
  `winner_id` int(11) DEFAULT NULL,
  `match_status` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `challenger_id` (`challenger_id`),
  KEY `acceptor_id` (`acceptor_id`),
  KEY `acceptor_partner_id` (`acceptor_partner_id`),
  KEY `challenger_partner_id` (`challenger_partner_id`),
  KEY `tennis_match_ibfk_5` (`winner_id`),
  CONSTRAINT `tennis_match_ibfk_1` FOREIGN KEY (`challenger_id`) REFERENCES `user` (`id`),
  CONSTRAINT `tennis_match_ibfk_2` FOREIGN KEY (`acceptor_id`) REFERENCES `user` (`id`),
  CONSTRAINT `tennis_match_ibfk_3` FOREIGN KEY (`acceptor_partner_id`) REFERENCES `user` (`id`),
  CONSTRAINT `tennis_match_ibfk_4` FOREIGN KEY (`challenger_partner_id`) REFERENCES `user` (`id`),
  CONSTRAINT `tennis_match_ibfk_5` FOREIGN KEY (`winner_id`) REFERENCES `user` (`id`)
)